name: Enforce PR Source Branch

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-source-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is from 'dev' branch
        run: |
          # Check if the source branch of the PR is 'dev'
          if [[ "${{ github.head_ref }}" != "dev" ]]; then
            echo "Error: PR must be from the 'dev' branch"
            exit 1  # This will fail the action, blocking the PR
          fi
